name: audio_call_task
description: "A Flutter app featuring reels-style audio playback and real-time voice calling."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.2.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  flutter_bloc: ^8.1.3
  equatable: ^2.0.5
  just_audio: ^0.9.36
  audio_session: ^0.1.16

  flutter_local_notifications: ^16.3.2
  agora_rtc_engine: ^6.3.2
  permission_handler: ^11.0.1
  uuid: ^4.2.1

  # App rename utility
  rename_app: ^1.6.5
  dio: ^5.4.0


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

  # App icon generator
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true

  assets:
    - assets/reels_audio_call_icon.png

flutter_launcher_icons:
  android: true
  ios: true
  remove_alpha_ios: true
  image_path: assets/reels_audio_call_icon.png
